/* Football Legacy compatibility + career-state patch. */
(function(){
const I=()=>document.getElementById('game'),W=()=>I().contentWindow,D=()=>W().document;
const STATES=['Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming'];
function norm(){const w=W(),h=w.c&&w.c.hs;if(!h)return;h.classYear=h.classYear||'Freshman';h.year=h.year||1;h.week=Number(h.week)||0;h.level=h.level==='Varsity'?'Varsity':'JV';h.varsityGames=Number(h.varsityGames)||0;h.seasonDone=!!h.seasonDone;h.fallCampDone=!!h.fallCampDone;h.careerPhase=h.careerPhase||'highSchool';h.wear=Math.max(0,Math.min(100,Number(h.wear)||0));h.energy=Math.max(0,Number(h.energy)||6);h.confidence=Math.max(0,Math.min(100,Number(h.confidence)||50));h.coachTrust=Math.max(0,Math.min(100,Number(h.coachTrust)||50));h.chemistry=Math.max(0,Math.min(100,Number(h.chemistry)||65));w.save()}
function tip(t,x){const w=W(),d=D();if(localStorage.getItem('FL_tip_'+t))return;const b=d.createElement('div');b.style='position:fixed;right:18px;bottom:18px;z-index:99999;max-width:340px;background:#151c26;border:1px solid #354151;border-radius:12px;padding:15px;color:white;box-shadow:0 12px 30px #0008';b.innerHTML='<b>'+t+'</b><br><span style="color:#aeb8c6">'+x+'</span><br><button id="fltip">GOT IT</button>';d.body.appendChild(b);b.querySelector('#fltip').onclick=()=>{localStorage.setItem('FL_tip_'+t,'1');b.remove()}}
function patch(){const w=W();if(!w.start)return;norm();if(!w.__FLstart){w.__FLstart=1;const old=w.start;w.start=function(){w.c={};localStorage.removeItem('footballLegacyCareer');w.schoolRolls=0;w.coachRolls=0;old();setTimeout(()=>{const s=D().getElementById('state');if(s&&s.tagName==='INPUT'){const n=D().createElement('select');n.id='state';n.innerHTML=STATES.map(x=>'<option>'+x+'</option>').join('');s.replaceWith(n)}tip('Player Creation','All 50 states are available. Your position has its own important attributes, and your archetype is permanent.')},0)}}
if(!w.__FLcareer){w.__FLcareer=1;const oldSave=w.saveCoach;w.saveCoach=function(){oldSave();norm();const h=w.c.hs;h.level='JV';h.fallCampDone=false;h.week=0;h.varsityGames=0;h.classYear='Freshman';h.year=1;h.seasonDone=false;h.careerPhase='highSchool';w.save();runCamp()};
function runCamp(){const d=D(),h=w.c.hs,p=w.c.player;d.getElementById('app').innerHTML='<div class="page-title">FRESHMAN FALL CAMP</div><div class="subtitle">Your first chance to earn Varsity.</div><div class="panel"><h2>STARTING STATUS</h2><div class="notice"><b>'+p.firstName+' '+p.lastName+'</b> • '+p.position+' • '+p.archetype+'<br>Starting status: <b>JV</b></div><p>Fall Camp is simulated. Your attributes, archetype and coach development focus determine whether you earn Varsity.</p><button class="menu-button" id="campRun">RUN FALL CAMP</button></div>';d.getElementById('campRun').onclick=()=>{const a=p.attributes||{},v=Object.values(a).filter(x=>typeof x==='number'),avg=v.reduce((x,y)=>x+y,0)/Math.max(1,v.length),score=avg+Math.random()*20+(w.c.coach.development-3)*3;h.fallCampScore=Math.round(score);h.fallCampDone=true;h.level=score>=62?'Varsity':'JV';if(h.level==='Varsity')h.coachTrust=Math.min(100,h.coachTrust+8);w.save();w.hub();tip('Career Hub','Energy is your weekly time budget. Recovery reduces Wear & Tear; it never restores Energy.')}};
const oldHub=w.hub;w.hub=function(){norm();const h=w.c.hs;if(h.classYear==='Freshman'&&!h.fallCampDone){runCamp();return}oldHub();const d=D();d.querySelectorAll('button').forEach(b=>{if((b.textContent||'').includes('VIEW SEASON REVIEW'))b.remove()});if(h.week>=9&&!h.seasonDone){const b=d.createElement('button');b.className='menu-button';b.textContent='FRESHMAN SEASON REVIEW';b.onclick=()=>w.review();d.getElementById('app').appendChild(b)}};
const oldReview=w.review;w.review=function(){norm();const h=w.c.hs;if(h.classYear==='Freshman'&&h.week<9){alert('Season Review unlocks after all 9 regular-season games.');return}oldReview()};
const oldOff=w.offseason;w.offseason=function(){norm();if(!w.c.hs.seasonDone){alert('Finish the season before entering the offseason.');return}oldOff();norm();w.c.hs.classYear='Sophomore';w.c.hs.year=2;w.c.hs.careerPhase='highSchool';w.c.hs.week=0;w.c.hs.seasonDone=false;w.c.hs.fallCampDone=true;w.save();w.hub()};
const oldPlay=w.playGame;w.playGame=function(sim){norm();if(!w.c.hs.fallCampDone){alert('Finish Fall Camp first.');return}if(w.c.hs.week>=9){alert('The 9-game regular season is complete.');return}oldPlay(sim)};}
if(!w.__FLovr){w.__FLovr=1;w.ovr=function(){const p=w.c&&w.c.player;if(!p)return 60;const a=p.attributes||{},k={QB:['Awareness','Football IQ','Technique','Discipline','Power','Speed'],RB:['Speed','Acceleration','Agility','Power','Awareness','Football IQ'],WR:['Speed','Acceleration','Agility','Technique','Awareness','Football IQ'],TE:['Strength','Power','Technique','Awareness','Speed','Toughness'],OL:['Strength','Power','Technique','Awareness','Toughness'],DL:['Speed','Acceleration','Power','Strength','Technique','Toughness'],LB:['Awareness','Toughness','Strength','Speed','Football IQ','Technique'],DB:['Speed','Agility','Technique','Awareness','Football IQ'],K:['Power','Technique','Discipline','Football IQ'],P:['Power','Technique','Discipline','Awareness']}[w.role()]||Object.keys(a),avg=k.reduce((s,x)=>s+(a[x]||50),0)/k.length,target=60+Math.floor((avg-50)/8),old=Number(p.overall)||60;p.overall=Math.max(60,Math.min(99,old+(target>old?1:target<old?-1:0)));return p.overall}}
}
I().addEventListener('load',()=>setTimeout(patch,50));setInterval(patch,500);
})();